[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Law: Understanding the Legal Challenges and Opportunities of Intelligent Technologies"
